
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int SQUARE = 6;
  public static final int CHART = 10;
  public static final int CURVE = 12;
  public static final int SUMA = 13;
  public static final int CIRCLE = 5;
  public static final int COLOR = 2;
  public static final int COMA = 18;
  public static final int POLYGON = 9;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int CLOSEPARENTHESIS = 4;
  public static final int DIV = 16;
  public static final int RECTANGLE = 7;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int LINE = 8;
  public static final int ANIMATE = 11;
  public static final int OPENPARENTHESIS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COLOR",
  "OPENPARENTHESIS",
  "CLOSEPARENTHESIS",
  "CIRCLE",
  "SQUARE",
  "RECTANGLE",
  "LINE",
  "POLYGON",
  "CHART",
  "ANIMATE",
  "CURVE",
  "SUMA",
  "MINUS",
  "TIMES",
  "DIV",
  "NUMBER",
  "COMA"
  };
}

